### ISSUE TITLE
[DEPR]: Remove Persistent Course Grades Flags

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#29]
### Proposal Date

29 March 2021

### Ticket Acceptance Date

21 April 2021

### Technology Removal Date

TBD

### First Open edX Named Release Without This Functionality

TBD

### Rationale

From ticket [EDUCATOR-5627](https://openedx.atlassian.net/browse/EDUCATOR-5627) and [related slack thread](https://edx-internal.slack.com/archives/CD89W7Z7F/p1616696002150600):

The PersistentGradesEnabledFlag enables storing of subsection/course grades in Django, removing reliance on caching/recalculations each time a grade is requested. The flag (plus course-specific overrides) was created to control rollout, but has been enabled on the edX site since Feb 16, 2017.

It is currently not default enabled across Open edX instances.

### Removal

Proposal is to remove the PersistentGradesEnabledFlag, effectively enabling the feature across all Open edX instances. The course-specific override, CoursePersistentGradesFlag, and the related waffle flag, ASSUME_ZERO_IF_ABSENT, should also be removed.

Pre-work has already been done in [this edx-platform branch](https://github.com/edx/edx-platform/compare/nsprenkle/remove-persistent-grades-flag).

### Replacement

N/A

### Migration

The cutover requires a backfill job as specified [in this tutorial, introduced in Hawthorne](https://openedx.atlassian.net/wiki/spaces/AC/pages/755171487/WIP%3A+How+to+Enable+Persistent+Grades+in+Hawthorne). Effectively, it runs a batched grade calculation so that grades (which are assumed to be in Django) are found instead of raising exceptions.

Following the backfill job, the feature flags can be turned on/removed.

### Additional Info

Original Jira Ticket: https://openedx.atlassian.net/browse/DEPR-152

**Comment by feanil** [comment]
> Dave Ormsbee (TCRIL) 
> 8 days ago
> 
> Coincidentally, the fact that persistent grades aren’t enabled by default came up just last week for us at tCRIL. We’re very interested in seeing this one land. :slight_smile: Is it accurate to say that the first step (defaulting the flag to be enabled) would at least start new sites off with the correct setting, and we should do that and make a note for Nutmeg that they will have to set some configuration value to keep the old behavior if they want to put off migration? Do you have an updated sense of the timeline for this DEPR overall?
> 
> Thank you.

**Comment by matthugs** [comment]
@mattcarter may be a good person to help direct that question to the right audience.

**Comment by sambapete** [comment]
I hope I am not too late to the party, but this might cause me some headaches when moving from Native (Koa) to Tutor (Maple or Nutmeg) and also from PDF certificates to HTML certificates. I may require some steps or commands to allow me to migrate my courses since I have tons of course offerings that do not have persistent grades yet and that autogenerate certificates.

See my post here [From Native to Tutor, from PDF to HTML certificates and to Persist Grades or not](https://discuss.openedx.org/t/from-native-to-tutor-from-pdf-to-html-certificates-and-to-persist-grades-or-not/6872) 

Also see [Enable Automatic Certificate Generation is fail on Maple after Lilac upgrade](https://discuss.openedx.org/t/enable-automatic-certificate-generation-is-fail-on-maple-after-lilac-upgrade/6393/6)  

As Feanil and Dave well know, I have some historical perspective as our Open edX instance has been running since May 2015.

I guess I will need some kind of roadmap as to what to do and when to do it for my old courses without persistent grades and still ongoing and still delivering certificates.

**Comment by sambapete** [comment]
@feanil I will give it a try later on today or early next week on the instance I've set up to "try out" our Native to Tutor migration. We've encountered a few issues, nothing unsolvable thus far, because of the way our data and environment were setup and used since Aspen. We want this to be as transparent as possible for our course creators and our students.

I hope the command to backfill the grades will allow me to generate certificates for our old courses. Thus far I have only been able to do it for new courses where the "Certificates Display Behaviour" and "Certificates Available Date" fields appear on the "Dates & Details" section in Studio. I hope this is not a hidden dependency or a feature that only makes it work on courses created after the switch to HTML certificates with or without persistent grades enabled. That would be a logistical nightmare to recreate long standing courses and planning the migration from Native (Koa-PDF) to Tutor (Maple-HTML). Fingers crossed.

And sorry for originally creating my comments on the old DEPR page. I originally missed your comment about moving the issue to the new DEPR board.

**Comment by sambapete** [comment]
I may or I may not have something. Thanks for the suggestion @feanil 

I definitely need to enable the persistent grades on some courses and recalculate the grades for those courses that will switch from PDF certificates to HTML certificates when we move from Koa under Native to Maple or Nutmeg under Tutor. According to my first tests, the same course exported from Koa Native would have different behaviour when imported in Koa Tutor / Lilac Tutor then when imported in Maple Tutor.  It would make the Progress Page crash when I wanted to access it in order to request my certificate after successfully finishing the course. That's when I had to enable the Persistent Grades for that course, recalculate the grades for it, and voilà! No more Progress Page crash and I was able to autogenerate the HTML certificate.

I may need to retry my migration process to make sure our current courses that autogenerate certificates will survive the migration from Koa Native to Maple Tutor (or Nutmeg Tutor). Lots of things to check when your Open edX instance goes way back to Aspen.. It would be a breeze to start over from scratch, but it would get all political with our partners and our students.

**Comment by feanil** [comment]
@sambapete makes sense, if there are improvements we can make to the linked process please let us know, any polish we can add to make the transition easier for the community would be good.

**Comment by nsprenkle** [comment]
@feanil and @sambapete, we actually delayed the persistent course grade deprecation. This input is good. Probably worth turning it on by default and advertising this so there's a friendlier cutover period (if people need to disable and work on transition) before we remove the flag entirely.

**Comment by feanil** [comment]
@nsprenkle is there something holding up someone else doing this work?  Trying to understand if others can move it forward or if that would break something in some way for your team.

**Comment by feanil** [comment]
@dianakhuang @idegtiarov FYI, this is ready to be picked up.

**Comment by pdpinch** [comment]
What are the required steps for systems that have not yet turned on persistent grades, after the DEPR work in merged? 

Please include a note on the [olive wiki page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3396501578/Olive) so we can include instructions in the olive release notes.
